# Generated by Django 2.0.1 on 2021-01-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
